### ISSUE TITLE
which lib

### ISSUE THREAD

**Issue by skyladle** [LilyGO/TTGO-LORA32-V2.0#13]
which lib for this sample code ? thx :D

**Comment by donpdonp** [comment]
I had the same problem. After trying a few, I can say using the two following libraries works on my ttgo v2.0:

"Lora" by Sandeep Mistry
"SSD1306" by Alexey Dynda

**Comment by LilyGO** [comment]
https://github.com/ThingPulse/esp8266-oled-ssd1306

**Comment by LilyGO** [comment]
https://github.com/sandeepmistry/arduino-LoRa

**Comment by apiel** [comment]
The screen is not working even with https://github.com/ThingPulse/esp8266-oled-ssd1306 :-/ 
Please could you update your readme and have the details step to setup the examples firmware.

**Comment by apiel** [comment]
ok it work with:

`SSD1306 display(0x3c, 4, 15);`

Why not to merge the pull request?
