### ISSUE TITLE
Provide all physical dimentions 

### ISSUE THREAD

**Issue by pablotecnoandina** [LilyGO/TTGO-LORA32-V2.0#16]
Hi Team

The TTGO-LoRa32-V2.0 is a great device and I use in many project, but now need a specific physical dimensions for create a shield for mount this device. Thank for you reply

**Comment by LilyGO** [comment]
![image](https://user-images.githubusercontent.com/31160602/50134967-6f473680-02cd-11e9-95a7-ecdaed9a69dd.png)

**Comment by sFischle** [comment]
Hi, 
what is the spacing between the pins? 

![grafik](https://user-images.githubusercontent.com/44380255/193470173-e24b5a5e-5ad1-4e3b-81c1-066a77daf738.png)
