### ISSUE TITLE
Temperature sensor pin

### ISSUE THREAD

**Issue by mranest** [LilyGO/TTGO-LORA32-V2.0#20]
Came back to this repository and found the bat test sample, which uses pin 35 to access the battery reading. Does anyone know the pin to read the temperature sensor reading? Allegedly both V2.0 and V2.1 boards have an onboard temperature sensor:

>...
>RF wake-up function
>Low voltage detection and **temperature sensor**
>Fast wake-up and frequency hopping
>...

**Comment by LilyGO** [comment]
Sorry, this is our work mistake. This product does not have onboard temperature measurement. We will correct it in time and cause problems for you. We apologize.

**Comment by mranest** [comment]
Ok. Thanks for replying!
